### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [astrapi69/mystic-crypt#46]
Hi
The following lines have cryptographic API misuses. <br> File name => crypt-core/src/main/java/de/alpharogroup/crypto/hex/HexableEncryptor.java: Line number => 164: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PublicKeyHexEncryptor.java: Line number => 136: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PublicKeyHexEncryptor.java: Line number => 111: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleEncryptor.java: Line number => 139: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleEncryptor.java: Line number => 103: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/hex/HexableDecryptor.java: Line number => 143: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/gm/GoogleMapsUrlSigner.java: Line number => 90: API name => SecretKeySpec:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleDecryptor.java: Line number => 139: API name => PBEParameterSpec:Second parameter (with value 19)Variable iterationCountmust be  at least 1000<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PublicKeyHexEncryptor.java: Line number => 111: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PrivateKeyHexDecryptor.java: Line number => 144: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleDecryptor.java: Line number => 103: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/gm/GoogleMapsUrlSigner.java: Line number => 140: API name => SecretKeySpec:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleDecryptor.java: Line number => 103: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/gm/GoogleMapsUrlSigner.java: Line number => 139: API name => SecretKeySpec:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/gm/GoogleMapsUrlSigner.java: Line number => 91: API name => SecretKeySpec:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleDecryptor.java: Line number => 138: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleEncryptor.java: Line number => 140: API name => PBEParameterSpec:Second parameter (with value 19)Variable iterationCountmust be  at least 1000<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PrivateKeyHexDecryptor.java: Line number => 117: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/simple/SimpleEncryptor.java: Line number => 103: API name => Cipher:<BR> File name => crypt-core/src/main/java/de/alpharogroup/crypto/key/PrivateKeyHexDecryptor.java: Line number => 117: API name => Cipher:<BR>

**Comment by jimmyMaci** [comment]
Dear @mhp0rtal, this is no misuses of cryptographic APIs what you describe above. For more information you can see the unit tests.

If there is an error please provide a PR.

I will close this issue.
