### ISSUE TITLE
New feature decorate encryption object with an decoration Object

### ISSUE THREAD

**Issue by jimmyMaci** [astrapi69/mystic-crypt#47]
Hi there,

create a decoration object with a prefix and suffix that decorates an encryption object.

For instance if i have a password 'foo-bar' and a decoration object with a prefix of '?' and a suffix '&' the result before the encryption would be '?foo-bar&', and for the decryption process it would be the same reversed process.

Cheers

James Phelps

**Comment by erikgajdos1997** [comment]
Hello, do you want to implement decorator object, which will modify the encrypted text with some chars as prefix and than as postfix? 
If it is still free, can I take this issue, could you assign me to this?

**Comment by astrapi69** [comment]
Hi @jimmyMaci, thats a great idea. I created a generic decorated object in the [crypt-data project](https://github.com/astrapi69/crypt-data/blob/develop/src/main/java/de/alpharogroup/crypto/model/CryptObjectDecorator.java) that can be used for this purpose.

If i have time i will implement it and provide an example.

**Comment by astrapi69** [comment]
Hi @jimmyMaci, i ve implemented this new feature request and is in the new minor release 7.2

So i will close this issue
