### ISSUE TITLE
Create url signer class for google maps

### ISSUE THREAD

**Issue by jimmyMaci** [astrapi69/mystic-crypt#6]
Here is the doku:

https://developers.google.com/maps/documentation/directions/get-api-key?hl=en#troubleshooting-authentication-issues

And an example class;

https://github.com/googlemaps/url-signing/blob/gh-pages/UrlSigner.java

**Comment by astrapi69** [comment]
Fixed with pr https://github.com/astrapi69/mystic-crypt/pull/43
